MyJournal/Controllers/SharingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyJournal.Data;
using MyJournal.Models;
using MyJournal.Models.CustomModels;
using MyJournal.Services;
using System.Linq;
using System.Threading.Tasks;

namespace MyJournal.Controllers
{
    [Authorize]
    public class SharingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private UserManager<ApplicationUser> _userManager;

        public SharingsController(ApplicationDbContext context, IEmailSender emailSender, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _emailSender = emailSender;
            _userManager = userManager;
        }

        public async Task<bool> CheckAuthAsync(Sharing sharing)
        {
            if (sharing.Giver == await _userManager.GetUserAsync(User))
            {
                return true;
            }
            return false;
        }

        //GET: Sharings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sharings
                .Where(m => m.Giver.Email == User.Identity.Name || m.Getter.Email == User.Identity.Name)
                .Include(m => m.Giver)
                .Include(m => m.Getter)
                .ToListAsync());
        }

        // GET: Sharings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sharing = await _context.Sharings
                .SingleOrDefaultAsync(m => m.SharingID == id);

            bool auth = await CheckAuthAsync(sharing);
            if (sharing == null || !auth)
            {
                return NotFound();
            }

            return View(sharing);
        }

        // GET: Sharings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sharings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SharingID,Receiver,PermissionLevel")] Sharing sharing)
        {
            if (ModelState.IsValid)
            {
                sharing.Giver = await _userManager.GetUserAsync(User);
                sharing.Getter = _userManager.Users.FirstOrDefault(u => u.Email == sharing.Receiver);

                string link = "<a href='https://mydailyjournal.azurewebsites.net/Sharings'>link</a>";
                string msg = $"{sharing.Giver.Email} has shared their My Journal with you. \nHere is their link: {link}";
                await _emailSender.SendEmailAsync(sharing.Receiver, "Someone shared with you on My Journal", msg);

                link = "<a href='https://mydailyjournal.azurewebsites.net/Manage/SetPassword'>link</a>";
                msg = $@"You have shared your MyJournal with {sharing.Receiver}\nIf this was not you, you can remove it here: {link}\nAlso reset your password here {link}";
                await _emailSender.SendEmailAsync(sharing.Getter.Email, "You Shared with Someone on My Journal", msg);

                _context.Add(sharing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sharing);
        }

        // GET: Sharings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sharing = await _context.Sharings
                .SingleOrDefaultAsync(m => m.SharingID == id);

            bool auth = await CheckAuthAsync(sharing);
            if (sharing == null || !auth)
            {
                return NotFound();
            }

            return View(sharing);
        }

        // POST: Sharings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sharing = await _context.Sharings.SingleOrDefaultAsync(m => m.SharingID == id);
            _context.Sharings.Remove(sharing);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SharingExists(int id)
        {
            return _context.Sharings.Any(e => e.SharingID == id);
        }
    }
}

MyJournal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyJournal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/moodSelector.css" />
        <link rel="stylesheet" href="~/css/DailyInformation-Index.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="bg-light">


    <nav class="navbar navbar-expand-md navbar-dark bg-custom border-bottom border-dark">
        <a class="navbar-brand abs" asp-area="" asp-controller="Home" asp-action="Index">My Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="collapsingNavbar">
            <ul class="navbar-nav">
                <li class="nav-item @Html.Raw(ViewBag.HomeActive)">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                        Home
                    </a>
                </li>
                <li class="nav-item @Html.Raw(ViewBag.AboutActive)">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">
                        About
                    </a>
                </li>
                <li class="nav-item @Html.Raw(ViewBag.ContactActive)">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">
                        Contact
                    </a>
                </li>
                <li class="nav-item @Html.Raw(ViewBag.ShareActive)">
                    <a class="nav-link" asp-area="" asp-controller="Sharings" asp-action="Index">
                        Sharing Center
                    </a>
                </li>
                <li class="nav-item @Html.Raw(ViewBag.AggregateActive)">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Aggregate">
                        Global Reports
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                @await Html.PartialAsync("_LoginPartial")
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        @RenderBody()
    </div>


    <footer class="bg-dark border-top border-light">
        
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/js/CustomTemplates.js" asp-append-version="true"></script>
        <script src="~/js/DailyInfornmation-Index.js" asp-append-version="true"></script>
        <script src="~/js/graph.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/jquery.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>