MyJournal/Controllers/SharedDailyInformationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyJournal.Data;
using System.Linq;
using System.Threading.Tasks;

namespace MyJournal.Controllers
{
    [Authorize]
    public class SharedDailyInformationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SharedDailyInformationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SharedDailyInformations
        public async Task<IActionResult> Index(string giverName)
        {
            var sharings = _context.Sharings
                .Include(m => m.Giver)
                .Include(m => m.Getter)
                .FirstOrDefault(x => x.Giver.Email == giverName);
            if (sharings != null && sharings.Receiver == User.Identity.Name)
            {
                return View(await _context.DailyInformations.Where(x => x.ApplicationUser == sharings.Giver).ToListAsync());
            }
            return View();
        }

        // GET: SharedDailyInformations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dailyInformation = await _context.DailyInformations
                .Include(m => m.ApplicationUser)
                .SingleOrDefaultAsync(m => m.DailyInformationID == id);

            var auth = _context.Sharings
                .Include(m => m.Giver)
                .Include(m => m.Getter)
                .FirstOrDefault(x => x.Giver.Email == dailyInformation.ApplicationUser.Email && x.Getter.Email == User.Identity.Name);

            if (dailyInformation == null || auth == null)
            {
                return NotFound();
            }

            return View(dailyInformation);
        }
    }
}

MyJournal/Views/SharedDailyInformations/Details.cshtml
@model MyJournal.Models.CustomModels.DailyInformation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DailyInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JournalText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JournalText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DailyInformationDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DailyInformationDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserMood)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserMood)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GeneratedMood)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GeneratedMood)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MinExercising)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MinExercising)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HoursSlept)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HoursSlept)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DownTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DownTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MinPhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MinPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumGoodThings)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumGoodThings)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumPoorThings)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumPoorThings)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OverallDay)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OverallDay)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExcitedForTomorrow)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExcitedForTomorrow)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MinHobby)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MinHobby)
        </dd>
    </dl>
</div>
<div>
    <form id="giverName" asp-controller="SharedDailyInformations" asp-action="Index" method="post" role="form">
        <button type="submit" class="btn btn-info" name="giverName" value="@Model.ApplicationUser.Email">
            Back to list
        </button>
    </form>
</div>

MyJournal/Views/SharedDailyInformations/Index.cshtml
@model IEnumerable<MyJournal.Models.CustomModels.DailyInformation>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JournalText)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DailyInformationDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserMood)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GeneratedMood)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MinExercising)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HoursSlept)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DownTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MinPhone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumGoodThings)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumPoorThings)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OverallDay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExcitedForTomorrow)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MinHobby)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JournalText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DailyInformationDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserMood)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GeneratedMood)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinExercising)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoursSlept)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumGoodThings)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumPoorThings)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OverallDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExcitedForTomorrow)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinHobby)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.DailyInformationID">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>